### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto_atrapadosmillones#1]
Hola,

He revisado el README:

- La propuesta de trabajo es adecuada, aunque no demasiado original. Ya se han hecho varios trabajos similares en cursos anteriores. Adelante, pero tendréis que aportar originalidad en vuestra implementación.
- Eliminad los corchetes y el texto que contienen.
- En la lista de participantes usad el formato lista de Markdown.
- Podéis enlazar cada participante a su página web de GitHub.

**Comment by MiguelGV22** [comment]
Hola, 
ya creo que esta todo, quedo a la espera de confirmacion para cerrar la issue.

un saludo

**Comment by oscarperpinan** [comment]
Adelante. Todo en orden.

**Comment by MiguelGV22** [comment]
vale, cierro
