### ISSUE TITLE
Diagrama de flujo

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-proyecto_atrapadosmillones#3]
Debéis crear un fichero en formato [PDF](https://help.github.com/en/articles/rendering-pdf-documents), [GIF, JPEG o PNG](https://help.github.com/en/articles/rendering-and-diffing-images) (**no se admiten documentos Word o similar**) representando el [diagrama de flujo](https://es.wikipedia.org/wiki/Diagrama_de_flujo) previsto para vuestro programa. 
En el punto de inicio tenéis un [tutorial](https://github.com/aigora/punto_inicio/wiki/6.1-C%C3%B3mo-realizar-un-diagrama-de-flujo) para crear diagramas de flujo.
Este diagrama os servirá de guía para la implementación del trabajo. No obstante, ésta será la primera versión, por lo que según vayáis avanzando en el desarrollo del programa podréis y deberéis modificarlo.

**Comment by gonzalopeinado** [comment]
![Untitled Diagram (1)](https://user-images.githubusercontent.com/79969645/113850762-169c5000-979b-11eb-8d84-329edd3bc769.png)

**Comment by gonzalopeinado** [comment]
![Untitled Diagram (2)](https://user-images.githubusercontent.com/79969645/113851772-1fd9ec80-979c-11eb-8237-7a0796c45ace.png)

**Comment by oscarperpinan** [comment]
El diagrama debe estar en un fichero dentro del repositorio.

**Comment by oscarperpinan** [comment]
Este flujo de programa no tiene demasiado sentido. Siempre pasa a la siguiente pregunta (para eso no hace falta un diagrama), y está particularizado para 10 preguntas (¿cómo sería si fuesen 100 preguntas?).
Prestad atención a la ortografía. La pregunta 8ª necesita una **V**.

**Comment by MiguelGV22** [comment]
He modificado el diagrama de flujo, así esta mejor?
Puedo cerrar la issue?
