### ISSUE TITLE
Definición de las estructuras

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-proyecto_atrapadosmillones#5]
Debéis implementar la definición de las principales estructuras (datos tipo `struct`) que se usan en el programa.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by oscarperpinan** [comment]
Uno de los requisitos mínimos en el trabajo es:

> Es obligatorio utilizar vectores de estructuras. 

En vuestro código habéis definido las estructuras pero no estáis usando vectores de estructuras.
